package observability

const dashboardHTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RepoArk Fleet</title><style>
:root{color-scheme:dark;background:#0c0e12;color:#e9edf2;font-family:Inter,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;padding:24px;max-width:1400px;margin:auto}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}.brand{font-size:22px;font-weight:750}.muted{color:#8e99a8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card{background:#13171d;border:1px solid #252b35;border-radius:14px;padding:16px}.kpi{font-size:28px;font-weight:750;margin-top:8px}.ok{color:#7ee787}.bad{color:#ff7b72}.warn{color:#d29922}table{width:100%;border-collapse:collapse;margin-top:12px}td,th{text-align:left;padding:10px;border-bottom:1px solid #252b35;font-size:14px}button{border:1px solid #30363d;background:#1b2028;color:#e9edf2;border-radius:9px;padding:8px 12px}h2{font-size:15px;margin:22px 0 8px}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#222832;font-size:12px}@media(max-width:620px){body{padding:14px}.top{align-items:flex-start}.kpi{font-size:24px}td:nth-child(2),th:nth-child(2){display:none}}
</style></head><body><div class="top"><div><div class="brand">RepoArk Fleet</div><div class="muted">Backup health, RPO/RTO policy and recovery readiness</div></div><button onclick="load()">Refresh</button></div><div id="kpis" class="grid"></div><h2>Policy</h2><div id="policy" class="card">Loading…</div><h2>Accounts</h2><div class="card"><table><thead><tr><th>Account</th><th>Root</th><th>State</th><th>Repos</th><th>Warnings</th><th>Last backup</th></tr></thead><tbody id="fleet"></tbody></table></div><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function j(u){const r=await fetch(u,{cache:'no-store'});return await r.json()}
function age(d){if(!d)return'—';const n=(Date.now()-new Date(d).getTime())/1000;if(n<120)return Math.round(n)+'s';if(n<7200)return Math.round(n/60)+'m';if(n<172800)return Math.round(n/3600)+'h';return Math.round(n/86400)+'d'}
function fmt(n){const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return (i?n.toFixed(1):n)+' '+u[i]}
async function load(){let s,f,p,c;try{[s,f,p,c]=await Promise.all([j('/api/v1/status'),j('/api/v1/fleet'),j('/api/v1/policy'),j('/api/v1/control/stats')])}catch(e){document.querySelector('#policy').innerHTML='<span class="bad">API unavailable</span>';return}const m=s.manifest||{},good=s.ok;let k='';k+='<div class="card"><div class="muted">Overall</div><div class="kpi '+(good?'ok':'bad')+'">'+(good?'HEALTHY':'DEGRADED')+'</div></div>';k+='<div class="card"><div class="muted">Repositories</div><div class="kpi">'+(m.succeeded||0)+'/'+((m.repositories||[]).length)+'</div></div>';k+='<div class="card"><div class="muted">Last backup</div><div class="kpi">'+age(m.ended_at)+'</div></div>';k+='<div class="card"><div class="muted">CAS reclaimed</div><div class="kpi">'+fmt((m.cas&&m.cas.reclaimed_bytes)||0)+'</div></div>';if(c&&c.enabled){const x=c.stats||{};k+='<div class="card"><div class="muted">Control queue</div><div class="kpi">'+(x.queued_jobs||0)+' / '+(x.running_jobs||0)+'</div><div class="muted">queued / running · '+(x.stranded_jobs||0)+' stranded · '+(x.connected_agents||0)+' agents</div></div>'}document.querySelector('#kpis').innerHTML=k;document.querySelector('#policy').innerHTML=p.healthy?'<span class="ok">All policy gates pass</span>':(p.violations||[]).map(v=>'<div><span class="pill bad">'+esc(v.code)+'</span> '+esc(v.message)+'</div>').join('');const rows=f.accounts||[];document.querySelector('#fleet').innerHTML=rows.length?rows.map(a=>'<tr><td>'+esc(a.name)+'</td><td class="muted">'+esc(a.root)+'</td><td class="'+(a.ok?'ok':'bad')+'">'+(a.ok?'OK':'FAIL')+'</td><td>'+(a.succeeded||0)+'/'+((a.succeeded||0)+(a.failed||0))+'</td><td class="'+((a.warnings||0)>0?'warn':'')+'">'+(a.warnings||0)+'</td><td>'+age(a.ended_at)+'</td></tr>').join(''):'<tr><td colspan="6" class="muted">Fleet mode disabled; showing primary account only through status API.</td></tr>'}
load();setInterval(load,30000)
</script></body></html>`
